---
title: "Stress_Analysis_On_Reddit"
author: "Melanie McCord"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load required packages
library(tidytext)
library(tidyverse)
library(caret)
library(stringr)
source("./model_training_functions/train_test_split.R")
source("./feature_creation_functions/create_bag_of_words_model.R")
source("./feature_creation_functions/create_sentiment_model.R")
source("./data_visualization_functions/plot_frequency_distribution.R")
source("./feature_selection_functions/remove_overly_correlated_features.R")

```
Now let's start off by reading in the training and test data.
```{r}
test_data <- read_csv("reddit_stress_data/dreaddit-test.csv")
train_data <- read_csv("reddit_stress_data/dreaddit-test.csv")
reddit_stress_data <- inner_join(train_data, test_data)
```
First, I'll start by creating a bag of words representation on my data, marking unknown variables correspondingly.
```{r}
bag_of_words_with_unknowns <- CreateBagOfWordsWithUnknowns(reddit_stress_data)
```

Since we have our bag of words model, let's mutate to represent the proportion of words for that variable.
```{r}
stress_data_with_bow <- reddit_stress_data %>%
  select(-text) %>%
  left_join(bag_of_words_with_unknowns, by = "id")
head(stress_data_with_bow, 2)
```

